[package]
name = "advent-of-code-2020"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
index_list = "0.3.0"
test-case = "3.3.1"
thiserror = "2.0.17"
